# Any values in this configuration file (except numbers and booleans) can be encrypted using Base64 encoded AES-256.
# Use the command
# ./gitscanner -encrypt <input>
# to encrypt any input.

# General server configuration.
server:
  port: 16092                                 # The HTTP port to start the server on.
  # tls:                                        # When provided the endpoint will be using HTTPS.
  #   certFile: /home/thekoolhatkar/cert.pem       # Relative or absolute path of certificate (chain) in PEM format.
  #   privateKeyFile: /home/thekoolhatkar/key.pem # Relative or absolute path of private key in PEM format.

# Authentication methods to use when cloning repositories via Git.
auth:
  ssh:
    privateKeyFile: /home/thekoolhatkar/.ssh/id_rsa  # SSH private key file to use when cloning repositories.

# Configuration for every configurable check.
checks:
  - name: CheckCommitMetaInformation # The name of the check.
    enabled: true                    # If set to false this check is not allowed to be executed.
    config:                          # This configuration section varies for each check.
      commitSizeThresholdByte: 86457
      emailPattern: .*@github.com|naazibu@gitlab.com
      namePattern: .*
  - name: SearchBinaries
    enabled: false
    config:
      branchPattern: .*
  - name: SearchIllegalUnicodeCharacters
    enabled: true
    config:
      branchPattern: .*origin/develop
  - name: SearchBigFiles
    enabled: true
    config:
      branchPattern: .*origin/main|.*origin/feature_.*
      filesizeThresholdByte: 86457
