name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 17
        registry-url: https://registry.npmjs.org/
    
    - name: Build ui
      run: |
        cd ui
        npm install
        npm run build

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Linux
      run: GOOS=linux go build -o gitscanner -v .

    - name: Build Windows
      run: GOOS=windows go build -o gitscanner.exe -v .
