name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Linux
      run: GOOS=linux go build -o gitscanner -v .

    - name: Build Windows
      run: GOOS=windows go build -o gitscanner.exe -v .
