name: pre-release

on:
  push:
    branches: [ master ]

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Node
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 17
        registry-url: https://registry.npmjs.org/
    
    - name: Build ui
      run: |
        cd ui
        npm install
        npm run build

    - name: Build Linux
      run: GOOS=linux go build -o gitscanner -v .

    - name: Build Windows
      run: GOOS=windows go build -o gitscanner.exe -v .
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          gitscanner
          gitscanner.exe
