name: tagged-release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 17
        registry-url: https://registry.npmjs.org/
    
    - name: Build ui
      run: |
        npm install
        npm run build

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Linux
      run: GOOS=linux go build -o gitscanner -v .

    - name: Build Windows
      run: GOOS=windows go build -o gitscanner.exe -v .
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          gitscanner
          gitscanner.exe
