name: tagged-release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install mingw-w64
      run: sudo apt-get install -y mingw-w64

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 17
        registry-url: https://registry.npmjs.org/
    
    - name: Write version to file
      run: echo "$GITHUB_REF_NAME" > VERSION

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Build ui
      run: |
        cd ui
        npm install
        npm run build
    
    - name: Test Go
      run: go test -v ./...

    - name: Build Linux
      run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o gitscanner -v .

    - name: Build Windows
      run: CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ GOOS=windows GOARCH=amd64 go build -o gitscanner.exe -v .
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          gitscanner
          gitscanner.exe
